DROP EXTENSION IF EXISTS "uuid-ossp" CASCADE;
DROP EXTENSION IF EXISTS citext CASCADE;

DROP TABLE IF EXISTS collections_puzzles;
DROP TABLE IF EXISTS puzzle_solves;
DROP TABLE IF EXISTS puzzles;
DROP TABLE IF EXISTS collections;
DROP TABLE IF EXISTS tokens;
DROP TABLE IF EXISTS users;

DROP TYPE IF EXISTS visibility;
DROP TYPE IF EXISTS solve_status;
